/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cadena.java
 *
 * Created on 13-may-2013, 19:32:51
 */

package Desarrollo;

import java.awt.Frame;
import java.awt.event.KeyEvent;

/**
 *
 * @author alexanderdelriscomorales
 */
public class Cadena extends javax.swing.JDialog {

    public static int c;

   
    /** Creates new form Cadena */
    public Cadena(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(630, 132);
        this.setTitle("Numero Aleatorio");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        panelTranslucidoComplete1 = new org.edisoncor.gui.panel.PanelTranslucidoComplete();
        LabelCadenaAnalizada = new org.edisoncor.gui.label.LabelMetric();
        labelNumeroDecimal = new org.edisoncor.gui.label.LabelMetric();
        textFieldCadenaAnalizada = new org.edisoncor.gui.textField.TextField();
        textFieldNumeroDecimal = new org.edisoncor.gui.textField.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCadenaAnalizada = new javax.swing.JTextArea();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        jButtonCadenaSiguiente = new javax.swing.JButton();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        textFieldNumCadenasCadena = new org.edisoncor.gui.textField.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/textura1.jpg"))); // NOI18N

        panelShadow1.setDistance(8);

        panelTranslucidoComplete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Udistrital.jpeg"))); // NOI18N

        org.jdesktop.layout.GroupLayout panelTranslucidoComplete1Layout = new org.jdesktop.layout.GroupLayout(panelTranslucidoComplete1);
        panelTranslucidoComplete1.setLayout(panelTranslucidoComplete1Layout);
        panelTranslucidoComplete1Layout.setHorizontalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 97, Short.MAX_VALUE)
        );
        panelTranslucidoComplete1Layout.setVerticalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 77, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout panelShadow1Layout = new org.jdesktop.layout.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelShadow1Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(panelTranslucidoComplete1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelShadow1Layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(panelTranslucidoComplete1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        LabelCadenaAnalizada.setText("Numero Cadena");

        labelNumeroDecimal.setText("Numero Decimal");

        textFieldCadenaAnalizada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldCadenaAnalizada.setText("Numero  Cadena");
        textFieldCadenaAnalizada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldCadenaAnalizadaMouseClicked(evt);
            }
        });
        textFieldCadenaAnalizada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadenaAnalizadaActionPerformed(evt);
            }
        });
        textFieldCadenaAnalizada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldCadenaAnalizadaKeyTyped(evt);
            }
        });

        textFieldNumeroDecimal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldNumeroDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldNumeroDecimalMouseClicked(evt);
            }
        });
        textFieldNumeroDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumeroDecimalActionPerformed(evt);
            }
        });
        textFieldNumeroDecimal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldNumeroDecimalKeyTyped(evt);
            }
        });

        jTextAreaCadenaAnalizada.setColumns(20);
        jTextAreaCadenaAnalizada.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCadenaAnalizada);

        labelMetric1.setText("Cadena Analizada");

        jButtonCadenaSiguiente.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jButtonCadenaSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadenaSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Tick (1).png"))); // NOI18N
        jButtonCadenaSiguiente.setText("Analizar");
        jButtonCadenaSiguiente.setBorderPainted(false);
        jButtonCadenaSiguiente.setContentAreaFilled(false);
        jButtonCadenaSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadenaSiguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCadenaSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadenaSiguienteActionPerformed(evt);
            }
        });

        labelMetric2.setText("Numero de Cadenas");

        textFieldNumCadenasCadena.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldNumCadenasCadena.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textFieldNumCadenasCadena.setEnabled(false);
        textFieldNumCadenasCadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumCadenasCadenaActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panel1Layout = new org.jdesktop.layout.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(textFieldCadenaAnalizada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(LabelCadenaAnalizada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelNumeroDecimal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jButtonCadenaSiguiente)
                        .add(textFieldNumeroDecimal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(textFieldNumCadenasCadena, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(labelMetric2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(53, 53, 53)
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(panel1Layout.createSequentialGroup()
                        .add(labelMetric1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(panelShadow1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(panel1Layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 259, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(78, 78, 78)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1Layout.createSequentialGroup()
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panel1Layout.createSequentialGroup()
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(LabelCadenaAnalizada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelNumeroDecimal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelMetric1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelMetric2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, panel1Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(panelShadow1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 95, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panel1Layout.createSequentialGroup()
                        .add(panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(textFieldCadenaAnalizada, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(textFieldNumeroDecimal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(textFieldNumCadenasCadena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(65, 65, 65)
                        .add(jButtonCadenaSiguiente))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCadenaAnalizadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadenaAnalizadaActionPerformed
        // TODO add your handling code here:
        String s = textFieldCadenaAnalizada.getText();
    }//GEN-LAST:event_textFieldCadenaAnalizadaActionPerformed

    private void textFieldNumeroDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumeroDecimalActionPerformed
        // TODO add your handling code here:

         


    }//GEN-LAST:event_textFieldNumeroDecimalActionPerformed

    private void jButtonCadenaSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadenaSiguienteActionPerformed
        // TODO add your handling code here:
        

        try{
            
            Bina_Deci x = new Bina_Deci("1001000111010001001100011000011001100111000111010000000110101011101110111011111000000101001110110100110111111011000010100000000011010001101110010110011010001111000000110100011000110111110110100110100011110000010010011000010111001011010000101100000001001110001110101010011011000010101101101000100101010010010010110111001010100110000101001111001101001011011011010010110100101001011001010001111101011000100000110111100011000111010000011010101001010100000011001001000010000110100111000010010011100101111011010101001010101111011101001010010100100001111101111110000001101101011000001011110001100000101001001110110111110101011001111100110110011010111010011011001010100011111000010011100010101110110011010001110001110101000000011001110111101110000011001110100000011011111000100010010100011100001110011111101000010000110000011101111110111110111101010000011011100100101101011001010001010011011011000100100011000011000101101100001100010101000111110101100011100000110011011001011000101001010100000100000101001111");
	    int j = x.Calcular();
            String mynumero = Integer.toString(j);
            textFieldNumeroDecimal.setText(mynumero);

            }catch(Exception e){

            textFieldCadenaAnalizada.setText("REGISTRE CADENA");
           }
        
    }//GEN-LAST:event_jButtonCadenaSiguienteActionPerformed

    private void textFieldNumCadenasCadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumCadenasCadenaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textFieldNumCadenasCadenaActionPerformed

    private void textFieldCadenaAnalizadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldCadenaAnalizadaKeyTyped
        // TODO add your handling code here:

        char caracter = evt.getKeyChar();
        if(((caracter < '1') ||(caracter > '9')) &&(caracter != KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_textFieldCadenaAnalizadaKeyTyped

    private void textFieldNumeroDecimalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldNumeroDecimalKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_textFieldNumeroDecimalKeyTyped

    private void textFieldNumeroDecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldNumeroDecimalMouseClicked
        // TODO add your handling code here:
        Bina_Deci x = new Bina_Deci("1001000111010001001100011000011001100111000111010000000110101011101110111011111000000101001110110100110111111011000010100000000011010001101110010110011010001111000000110100011000110111110110100110100011110000010010011000010111001011010000101100000001001110001110101010011011000010101101101000100101010010010010110111001010100110000101001111001101001011011011010010110100101001011001010001111101011000100000110111100011000111010000011010101001010100000011001001000010000110100111000010010011100101111011010101001010101111011101001010010100100001111101111110000001101101011000001011110001100000101001001110110111110101011001111100110110011010111010011011001010100011111000010011100010101110110011010001110001110101000000011001110111101110000011001110100000011011111000100010010100011100001110011111101000010000110000011101111110111110111101010000011011100100101101011001010001010011011011000100100011000011000101101100001100010101000111110101100011100000110011011001011000101001010100000100000101001111");
	 int j = x.Calcular();
         String mynumero = Integer.toString(j);
         textFieldNumeroDecimal.setText(mynumero);
        
    }//GEN-LAST:event_textFieldNumeroDecimalMouseClicked

    private void textFieldCadenaAnalizadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldCadenaAnalizadaMouseClicked
        // TODO add your handling code here:
        textFieldCadenaAnalizada.setText("");
    }//GEN-LAST:event_textFieldCadenaAnalizadaMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {


            @Override
            public void run() {
                Cadena dialog = new Cadena(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.label.LabelMetric LabelCadenaAnalizada;
    public javax.swing.JButton jButtonCadenaSiguiente;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextAreaCadenaAnalizada;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelNumeroDecimal;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    private org.edisoncor.gui.panel.PanelTranslucidoComplete panelTranslucidoComplete1;
    public org.edisoncor.gui.textField.TextField textFieldCadenaAnalizada;
    public org.edisoncor.gui.textField.TextField textFieldNumCadenasCadena;
    public org.edisoncor.gui.textField.TextField textFieldNumeroDecimal;
    // End of variables declaration//GEN-END:variables

}
