/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Vprincipal.java
 *
 * Created on 30-abr-2013, 21:15:05
 */
package Desarrollo;

/**
 *
 * @author alexanderdelriscomorales
 */
public class Vprincipal extends javax.swing.JFrame {

	/** Creates new form Vprincipal */
	public Vprincipal() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panelShadow1 = new org.edisoncor.gui.panel.PanelShadow();
        panelTranslucidoComplete1 = new org.edisoncor.gui.panel.PanelTranslucidoComplete();
        botonCadenas = new javax.swing.JButton();
        botonCifrador = new javax.swing.JButton();
        botonPruebasNist = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelShadow2 = new org.edisoncor.gui.panel.PanelShadow();
        botonAdministracion = new javax.swing.JButton();
        botonAcercade = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Floorboard & Wall - Green by ABH 1680x1050.jpg"))); // NOI18N

        panelShadow1.setDistance(10);
        panelShadow1.setOpaque(true);

        panelTranslucidoComplete1.setColorPrimario(new java.awt.Color(51, 102, 0));

        botonCadenas.setForeground(new java.awt.Color(255, 255, 255));
        botonCadenas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cadenas.png"))); // NOI18N
        botonCadenas.setText("Cadenas");
        botonCadenas.setBorder(null);
        botonCadenas.setContentAreaFilled(false);
        botonCadenas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCadenas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCadenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCadenasActionPerformed(evt);
            }
        });

        botonCifrador.setForeground(new java.awt.Color(255, 255, 255));
        botonCifrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cifrador.png"))); // NOI18N
        botonCifrador.setText("Cifrador");
        botonCifrador.setBorder(null);
        botonCifrador.setContentAreaFilled(false);
        botonCifrador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonCifrador.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonCifrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCifradorActionPerformed(evt);
            }
        });

        botonPruebasNist.setForeground(new java.awt.Color(255, 255, 255));
        botonPruebasNist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pruebas.png"))); // NOI18N
        botonPruebasNist.setText("Pruebas del NIST");
        botonPruebasNist.setBorder(null);
        botonPruebasNist.setContentAreaFilled(false);
        botonPruebasNist.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPruebasNist.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPruebasNist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPruebasNistActionPerformed(evt);
            }
        });

        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_exit.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setBorder(null);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.layout.GroupLayout panelTranslucidoComplete1Layout = new org.jdesktop.layout.GroupLayout(panelTranslucidoComplete1);
        panelTranslucidoComplete1.setLayout(panelTranslucidoComplete1Layout);
        panelTranslucidoComplete1Layout.setHorizontalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelTranslucidoComplete1Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(panelTranslucidoComplete1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, botonSalir, 0, 0, Short.MAX_VALUE)
                    .add(panelTranslucidoComplete1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, botonCifrador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, botonPruebasNist, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, botonCadenas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelTranslucidoComplete1Layout.setVerticalGroup(
            panelTranslucidoComplete1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelTranslucidoComplete1Layout.createSequentialGroup()
                .add(41, 41, 41)
                .add(botonCadenas)
                .add(31, 31, 31)
                .add(botonPruebasNist)
                .add(45, 45, 45)
                .add(botonCifrador)
                .add(36, 36, 36)
                .add(botonSalir)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout panelShadow1Layout = new org.jdesktop.layout.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelShadow1Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(panelTranslucidoComplete1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelShadow1Layout.createSequentialGroup()
                .add(panelTranslucidoComplete1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelShadow2.setDistance(5);

        botonAdministracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/64px-Plataformas.png"))); // NOI18N
        botonAdministracion.setText("Administracion");
        botonAdministracion.setBorderPainted(false);
        botonAdministracion.setContentAreaFilled(false);
        botonAdministracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAdministracion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        botonAcercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoInformacion_1.png"))); // NOI18N
        botonAcercade.setText("Acerca de");
        botonAcercade.setBorderPainted(false);
        botonAcercade.setContentAreaFilled(false);
        botonAcercade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAcercade.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.layout.GroupLayout panelShadow2Layout = new org.jdesktop.layout.GroupLayout(panelShadow2);
        panelShadow2.setLayout(panelShadow2Layout);
        panelShadow2Layout.setHorizontalGroup(
            panelShadow2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelShadow2Layout.createSequentialGroup()
                .add(55, 55, 55)
                .add(botonAdministracion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(botonAcercade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelShadow2Layout.setVerticalGroup(
            panelShadow2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelShadow2Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .add(panelShadow2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, botonAdministracion, 0, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, botonAcercade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE))
                .add(24, 24, 24))
        );

        org.jdesktop.layout.GroupLayout panel1Layout = new org.jdesktop.layout.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1Layout.createSequentialGroup()
                .add(115, 115, 115)
                .add(panelShadow1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(266, 266, 266)
                .add(panelShadow2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(148, 148, 148))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1Layout.createSequentialGroup()
                .add(panelShadow1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(675, Short.MAX_VALUE)
                .add(panelShadow2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(102, 102, 102))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void botonCadenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCadenasActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_botonCadenasActionPerformed

        private void botonPruebasNistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPruebasNistActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_botonPruebasNistActionPerformed

        private void botonCifradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCifradorActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_botonCifradorActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Vprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {


			public void run() {
				new Vprincipal().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAcercade;
    public javax.swing.JButton botonAdministracion;
    public javax.swing.JButton botonCadenas;
    public javax.swing.JButton botonCifrador;
    public javax.swing.JButton botonPruebasNist;
    public javax.swing.JButton botonSalir;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow1;
    private org.edisoncor.gui.panel.PanelShadow panelShadow2;
    private org.edisoncor.gui.panel.PanelTranslucidoComplete panelTranslucidoComplete1;
    // End of variables declaration//GEN-END:variables
}
